server:
  port: 8084

# for eureka server
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/


spring:
  cloud:
    gateway:
      httpclient:
        # time out configration as yml file
        connect-timeout: 1000
        response-timeout: 10s
      discovery:
        locator:
          enabled: true
          all-namespaces: true
          lowerCaseServiceId: true

  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/Fin_Tracker/protocol/openid-connect/certs





#enable all actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # for all actuator property
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}




logging:
  level:
    org:
      api:
        gateway: DEBUG


  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"